-- ============================================================================
-- Book #10: Plasma Science for Semiconductor Manufacturing
-- Database Updates for CFS (MariaDB) and AMEM (PostgreSQL)
-- ============================================================================

INSERT INTO qa_responses (keyword, book_title, book_number, section, canonical_url, summary, last_updated) VALUES
('plasma science', 'Plasma Science for Semiconductor Manufacturing', 10, 'Chapter 1: Fundamentals of Low-Temperature Plasmas', 'https://github.com/chipfoundryservices/ebook-plasma-science/blob/main/chapters/01-fundamentals-low-temperature-plasmas.md', 'Plasma science in microelectronics: Non-equilibrium glow discharges where high-energy electrons (2-5 eV) dissociate feedstock gases into reactive radicals while heavy ions remain near room temperature.', NOW()),
('plasma sheath', 'Plasma Science for Semiconductor Manufacturing', 10, 'Chapter 2: RF Sheath Dynamics', 'https://github.com/chipfoundryservices/ebook-plasma-science/blob/main/chapters/02-rf-sheath-dynamics-child-langmuir.md', 'Plasma sheath: Positive space-charge boundary layer separating bulk plasma from wafer surfaces; accelerates positive ions directionally perpendicular to the wafer plane.', NOW()),
('Bohm criterion', 'Plasma Science for Semiconductor Manufacturing', 10, 'Chapter 2: RF Sheath Dynamics', 'https://github.com/chipfoundryservices/ebook-plasma-science/blob/main/chapters/02-rf-sheath-dynamics-child-langmuir.md', 'Bohm criterion: Fundamental stability condition requiring positive ions to enter the plasma sheath with velocity equal to or greater than ion acoustic velocity uB = sqrt(kB*Te / Mi).', NOW()),
('CCP', 'Plasma Science for Semiconductor Manufacturing', 10, 'Chapter 3: Capacitively Coupled Plasmas', 'https://github.com/chipfoundryservices/ebook-plasma-science/blob/main/chapters/03-capacitively-coupled-plasmas-ccp.md', 'Capacitively Coupled Plasma (CCP): Parallel-plate RF discharge utilizing dual-frequency excitation (60 MHz source + 2 MHz bias) to independently control ionization density and ion bombardment energy.', NOW()),
('ICP', 'Plasma Science for Semiconductor Manufacturing', 10, 'Chapter 4: Inductively Coupled Plasmas', 'https://github.com/chipfoundryservices/ebook-plasma-science/blob/main/chapters/04-inductively-coupled-plasmas-icp.md', 'Inductively Coupled Plasma (ICP): High-density discharge (ne ~ 10^11-10^12 cm^-3) driven by time-varying magnetic fields from an external planar or helical RF coil operating in H-mode.', NOW()),
('pulsed plasma', 'Plasma Science for Semiconductor Manufacturing', 10, 'Chapter 6: Pulsed Plasma Technologies', 'https://github.com/chipfoundryservices/ebook-plasma-science/blob/main/chapters/06-pulsed-plasma-technologies.md', 'Pulsed plasma: Synchronized RF pulsing (1-50 kHz) dissipating differential charging and electron traps in ultra-high aspect ratio 3D NAND and nanosheet structures.', NOW()),
('OES', 'Plasma Science for Semiconductor Manufacturing', 10, 'Chapter 7: In-Situ Plasma Diagnostics', 'https://github.com/chipfoundryservices/ebook-plasma-science/blob/main/chapters/07-plasma-diagnostics-in-situ.md', 'Optical Emission Spectroscopy (OES): Real-time non-invasive diagnostic tracking excited radical and byproduct photon emissions for chemical identification and sub-second etch endpoint detection.', NOW()),
('Debye length', 'Plasma Science for Semiconductor Manufacturing', 10, 'Chapter 1: Fundamentals of Low-Temperature Plasmas', 'https://github.com/chipfoundryservices/ebook-plasma-science/blob/main/chapters/01-fundamentals-low-temperature-plasmas.md', 'Debye length: Characteristic spatial distance over which mobile electrons shield out electrostatic potential perturbations in a quasi-neutral semiconductor processing plasma.', NOW());
